<?php
session_start();
require_once '../../config/config.php';

if (!isLoggedIn() || !isAdmin()) {
    redirect('../../auth/login.php');
}

// Get parameters
$type = isset($_GET['type']) ? $_GET['type'] : 'summary';
$date_from = isset($_GET['date_from']) ? $_GET['date_from'] : date('Y-m-d', strtotime('-30 days'));
$date_to = isset($_GET['date_to']) ? $_GET['date_to'] : date('Y-m-d');

// Set headers for Excel download
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename="clearance_report_' . date('Y-m-d') . '.xls"');

// Start output buffering
echo '<html>';
echo '<meta charset="utf-8">';
echo '<body>';

if ($type == 'summary') {
    // SUMMARY REPORT
    ?>
    <table border="1" cellpadding="5" cellspacing="0">
        <tr>
            <th colspan="4" style="background-color: #800020; color: white; font-size: 16px;">
                GRADUATION CLEARANCE SYSTEM - SUMMARY REPORT
            </th>
        </tr>
        <tr>
            <td colspan="4">
                <strong>Report Date:</strong> <?php echo date('F d, Y'); ?><br>
                <strong>Date Range:</strong> <?php echo date('M d, Y', strtotime($date_from)); ?> - <?php echo date('M d, Y', strtotime($date_to)); ?><br>
                <strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['user_name']); ?>
            </td>
        </tr>
        <tr><td colspan="4"><br></td></tr>
        
        <!-- System Overview -->
        <tr>
            <th colspan="4" style="background-color: #800020; color: white;">SYSTEM OVERVIEW</th>
        </tr>
        <tr>
            <th>Metric</th>
            <th>Count</th>
            <th></th>
            <th></th>
        </tr>
        <?php
        $stmt = $pdo->query("SELECT COUNT(*) as count FROM users WHERE role = 'student'");
        $total_students = $stmt->fetch()['count'];
        
        $stmt = $pdo->query("SELECT COUNT(*) as count FROM departments WHERE is_active = 1");
        $total_departments = $stmt->fetch()['count'];
        
        $stmt = $pdo->query("SELECT COUNT(*) as count FROM clearance_items");
        $total_items = $stmt->fetch()['count'];
        ?>
        <tr><td>Total Students</td><td><?php echo number_format($total_students); ?></td><td></td><td></td></tr>
        <tr><td>Total Departments</td><td><?php echo $total_departments; ?></td><td></td><td></td></tr>
        <tr><td>Total Clearance Items</td><td><?php echo $total_items; ?></td><td></td><td></td></tr>
        <tr><td colspan="4"><br></td></tr>
        
        <!-- Clearance Statistics -->
        <tr>
            <th colspan="4" style="background-color: #800020; color: white;">CLEARANCE STATISTICS</th>
        </tr>
        <tr>
            <th>Metric</th>
            <th>Count</th>
            <th>Percentage</th>
            <th></th>
        </tr>
        <?php
        $stmt = $pdo->prepare("
            SELECT 
                COUNT(sc.id) as total_clearances,
                SUM(CASE WHEN sc.status = 'pending' THEN 1 ELSE 0 END) as pending,
                SUM(CASE WHEN sc.status = 'approved' THEN 1 ELSE 0 END) as approved,
                SUM(CASE WHEN sc.status = 'rejected' THEN 1 ELSE 0 END) as rejected,
                ROUND((SUM(CASE WHEN sc.status = 'approved' THEN 1 ELSE 0 END) / NULLIF(COUNT(sc.id), 0)) * 100, 1) as approval_rate
            FROM student_clearance sc
            WHERE DATE(sc.created_at) BETWEEN ? AND ?
        ");
        $stmt->execute([$date_from, $date_to]);
        $stats = $stmt->fetch();
        
        $total = $stats['total_clearances'] ?? 0;
        ?>
        <tr><td>Total Clearances</td><td><?php echo number_format($total); ?></td><td>100%</td><td></td></tr>
        <tr><td>Approved</td><td><?php echo number_format($stats['approved'] ?? 0); ?></td><td><?php echo $total > 0 ? round(($stats['approved'] / $total) * 100, 1) : 0; ?>%</td><td></td></tr>
        <tr><td>Pending</td><td><?php echo number_format($stats['pending'] ?? 0); ?></td><td><?php echo $total > 0 ? round(($stats['pending'] / $total) * 100, 1) : 0; ?>%</td><td></td></tr>
        <tr><td>Rejected</td><td><?php echo number_format($stats['rejected'] ?? 0); ?></td><td><?php echo $total > 0 ? round(($stats['rejected'] / $total) * 100, 1) : 0; ?>%</td><td></td></tr>
        <tr><td><strong>Approval Rate</strong></td><td colspan="3"><strong><?php echo $stats['approval_rate'] ?? 0; ?>%</strong></td></tr>
        <tr><td colspan="4"><br></td></tr>
        
        <!-- Department Performance -->
        <tr>
            <th colspan="4" style="background-color: #800020; color: white;">DEPARTMENT PERFORMANCE</th>
        </tr>
        <tr>
            <th>Department Name</th>
            <th>Code</th>
            <th>Total Clearances</th>
            <th>Approved</th>
            <th>Pending</th>
            <th>Rejected</th>
            <th>Completion Rate</th>
        </tr>
        <?php
        $stmt = $pdo->prepare("
            SELECT 
                d.department_name,
                d.department_code,
                COUNT(DISTINCT sc.id) as total_clearances,
                SUM(CASE WHEN sc.status = 'approved' THEN 1 ELSE 0 END) as approved,
                SUM(CASE WHEN sc.status = 'pending' THEN 1 ELSE 0 END) as pending,
                SUM(CASE WHEN sc.status = 'rejected' THEN 1 ELSE 0 END) as rejected,
                ROUND((SUM(CASE WHEN sc.status = 'approved' THEN 1 ELSE 0 END) / NULLIF(COUNT(DISTINCT sc.id), 0)) * 100, 1) as completion_rate
            FROM departments d
            LEFT JOIN clearance_items ci ON d.id = ci.department_id
            LEFT JOIN student_clearance sc ON ci.id = sc.clearance_item_id
            WHERE d.is_active = 1
            GROUP BY d.id
            ORDER BY completion_rate DESC
        ");
        $stmt->execute();
        $departments = $stmt->fetchAll();
        
        foreach ($departments as $dept):
        ?>
        <tr>
            <td><?php echo htmlspecialchars($dept['department_name']); ?></td>
            <td><?php echo $dept['department_code']; ?></td>
            <td><?php echo $dept['total_clearances']; ?></td>
            <td><?php echo $dept['approved']; ?></td>
            <td><?php echo $dept['pending']; ?></td>
            <td><?php echo $dept['rejected']; ?></td>
            <td><?php echo $dept['completion_rate']; ?>%</td>
        </tr>
        <?php endforeach; ?>
    </table>
    <?php
} else {
    // DETAILED REPORT
    ?>
    <table border="1" cellpadding="5" cellspacing="0">
        <tr>
            <th colspan="7" style="background-color: #800020; color: white; font-size: 16px;">
                GRADUATION CLEARANCE SYSTEM - DETAILED REPORT
            </th>
        </tr>
        <tr>
            <td colspan="7">
                <strong>Report Date:</strong> <?php echo date('F d, Y'); ?><br>
                <strong>Date Range:</strong> <?php echo date('M d, Y', strtotime($date_from)); ?> - <?php echo date('M d, Y', strtotime($date_to)); ?><br>
                <strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['user_name']); ?>
            </td>
        </tr>
        <tr><td colspan="7"><br></td></tr>
        
        <!-- Individual Clearance Records -->
        <tr>
            <th colspan="7" style="background-color: #800020; color: white;">INDIVIDUAL CLEARANCE RECORDS</th>
        </tr>
        <tr>
            <th>#</th>
            <th>Date</th>
            <th>Student Name</th>
            <th>Student ID</th>
            <th>Department</th>
            <th>Item</th>
            <th>Status</th>
        </tr>
        <?php
        $stmt = $pdo->prepare("
            SELECT 
                sc.*,
                u.full_name,
                u.student_id,
                d.department_name,
                ci.item_name
            FROM student_clearance sc
            JOIN users u ON sc.student_id = u.id
            JOIN clearance_items ci ON sc.clearance_item_id = ci.id
            JOIN departments d ON ci.department_id = d.id
            WHERE DATE(sc.created_at) BETWEEN ? AND ?
            ORDER BY sc.created_at DESC
        ");
        $stmt->execute([$date_from, $date_to]);
        $details = $stmt->fetchAll();
        
        $counter = 1;
        foreach ($details as $detail):
        ?>
        <tr>
            <td><?php echo $counter++; ?></td>
            <td><?php echo date('Y-m-d H:i', strtotime($detail['created_at'])); ?></td>
            <td><?php echo htmlspecialchars($detail['full_name']); ?></td>
            <td><?php echo $detail['student_id']; ?></td>
            <td><?php echo htmlspecialchars($detail['department_name']); ?></td>
            <td><?php echo htmlspecialchars($detail['item_name']); ?></td>
            <td><?php echo strtoupper($detail['status']); ?></td>
        </tr>
        <?php endforeach; ?>
        
        <?php if (empty($details)): ?>
        <tr>
            <td colspan="7" align="center">No records found for the selected date range</td>
        </tr>
        <?php endif; ?>
    </table>
    <?php
}

// Summary footer
if ($type == 'summary'):
?>
<br><br>
<table border="0" cellpadding="5">
    <tr>
        <td><strong>Report Summary</strong></td>
    </tr>
    <tr>
        <td>Total Departments: <?php echo count($departments); ?></td>
    </tr>
    <tr>
        <td>Top Performing Department: 
            <?php 
            if (!empty($departments)) {
                echo htmlspecialchars($departments[0]['department_name']) . ' (' . $departments[0]['completion_rate'] . '%)';
            } else {
                echo 'N/A';
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>Overall Approval Rate: <?php echo $stats['approval_rate'] ?? 0; ?>%</td>
    </tr>
</table>
<?php endif; ?>

<br><br>
<table border="0" cellpadding="5">
    <tr>
        <td align="center">
            <hr>
            <small>This report is system-generated by Graduation Clearance System<br>
            Generated on: <?php echo date('Y-m-d H:i:s'); ?><br>
            &copy; <?php echo date('Y'); ?> Graduation Clearance System - All Rights Reserved</small>
        </td>
    </tr>
</table>

<?php
echo '</body>';
echo '</html>';
?>